version: "3.9"

services:
  app:
    image: oven/bun:1
    container_name: chatapp-web
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db.supabase.internal:5432/postgres
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    networks:
      - default
      - supabase
    command: sh -c "bun install && bunx prisma generate && bunx next dev --webpack"

networks:
  supabase:
    external: true
    name: supabase_network_ChatApp
